### PR TITLE
Add robot status lcm message (superset of iiwa status)

### PR DESCRIPTION
**Pull request by gavincangan**

### CODE REVIEW

**Review by 5yler — APPROVED** [review]
LGTM but please add comments to robot_status_t.lcm with the different quantities

**Comment by duanyutong** [comment]
finally, we can start deprecating iiwa-specific types

**Comment by gavincangan** [comment]
> LGTM but please add comments to robot_status_t.lcm with the different quantities

Done

**Review by 5yler — APPROVED** [review]
LGTM platform & style

**Pull request merged**
