### PR TITLE
Remove dependency on bot_core

### PR DESCRIPTION
**Pull request by mpetersen94**

### CODE REVIEW

**Review by 5yler — APPROVED** [review]
LGTM platform & style
Would check with @duanyutong and @alanxzhou to make sure this won't break any LCM parsing needed for data reduction

**Review by duanyutong — COMMENTED** [review]
`stuffgetter_plan_t` is not used anywhere and can be deprecated. everything else lgtm

**Comment by mpetersen94** [comment]
By deprecated, does that mean removed?  Or is there a formal way to deprecate messages?

**Comment by 5yler** [comment]
Yes it can be removed

**Comment by duanyutong** [comment]
yes i meant removed

**Comment by gavincangan** [comment]
Removed `stuffgetter_plan_t`

**Review by duanyutong — APPROVED** [review]

**Pull request merged**
